# Generated by Django 5.1.4 on 2025-01-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=5000)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
